code --install-extension abusaidm.html-snippets
code --install-extension chris-noring.node-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension humao.rest-client
code --install-extension jasonnutter.search-node-modules
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension ms-azuretools.vscode-docker
code --install-extension p1c2u.docker-compose
code --install-extension piyushvscode.nodejs-snippets
code --install-extension prashaantt.node-tdd
code --install-extension redhat.java
code --install-extension ritwickdey.LiveServer
code --install-extension syler.sass-indented
code --install-extension TabNine.tabnine-vscode
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension xabikos.JavaScriptSnippets
